apiVersion: apps/v1
kind: Deployment
metadata:
  name: busapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: busapp-container
          image: ananddocker18/busapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
