apiVersion: v1
kind: Pod
metadata:
  name: busapp-pod
  labels:
     app: frontend
     project: infinity
spec:
  containers:
    - name: busapp-container
      image: kyrosbus
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
