apiVersion: v1
kind: Pod
metadata:
  name: busapp-pod
  labels:
     app: frontend
spec:
  containers:
    - name: busapp-container
      image: ananddocker18/busapp:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
