apiVersion: v1
kind: Service
metadata:
  name: busapp-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30005
  type: NodePort
