apiVersion: v1
kind: Service
metadata:
  name: busapp-service
spec:
  ports:
    - port: 30002
      targetPort: 3000
      nodePort: 30002
      protocol: TCP
  type: NodePort
  selector:
    app: frontend
